### ISSUE TITLE
EPERM problem on first start

### ISSUE THREAD

**Issue by FredRooks** [OpenSmartEnvironment/ose-example-rpi#2]
When the rpi example is run for the first time, the following error occurs. Restarting the example solves the problem. The bug is probably related to, if not caused by, the onoff library.

<pre><code>
rpi> 1444069210 'NOTICE | ose | CLI script finished.'
rpi> ========================================================
1444069217 'ERROR | ose | EPERM |' 'EPERM: operation not permitted, write'
Stack Trace:
Error: EPERM: operation not permitted, write
    at Error (native)
--------------------------------------------------------
Logged at:
Trace
    at Object.exports.error.exports.err (/home/ose/ose-example-rpi/node_modules/ose/lib/logger.js:276:11)
    at Object.exports.error (/home/ose/ose-example-rpi/node_modules/ose/lib/link.js:594:11)
    at /home/ose/ose-example-rpi/node_modules/ose-control/lib/pin/dout.js:106:14
    at /home/ose/ose-example-rpi/node_modules/ose-rpi/lib/rpi/node.js:286:7
    at FSReqWrap.strWrapper (fs.js:619:5)
========================================================
</code></pre>

**Comment by FredRooks** [comment]
Updating to the latest version of the onoff library seems to solve the problem.

**Comment by snaselj** [comment]
"onoff" in "ose-rpi" was updated to the latest version.
